export const kamus = {
  // Huruf dan Kata Dasar
  "a": "a_1", "b": "b-2", "c": "c-3", "d": "d_4", "e": "e#5", "f": "f$6", "g": "g@7", "h": "h&8", "i": "i!9", "j": "j^0", "k": "k~1", "l": "l<2", "m": "m>3", "n": "n%4", "o": "o*5", "p": "p-6", "q": "q_7", "r": "r#8", "s": "s$9", "t": "t@0", "u": "u&1", "v": "v!2", "w": "w^3", "x": "x~4", "y": "y<5", "z": "z>6",
  "ada": "*_@1", "adalah": "$#&!2", "akhir": "^$!7", "akhirnya": "*/_&!",
  "akan": "@_K$3", "aku": "#@&K!", "berani": "!#&@B", "pintar": "$%#@P",
  "bagus": "#@!%B", "jelek": "&*!@J", "cepat": "^$@!C", "lambat": "!@#$L",
  "sehat": "#$!@S", "sakit": "&*!@S", "panjang": "$%^#P", "pendek": "*!@#P",
  "besar": "#$!%B", "kecil": "&!@#K", "depan": "$#@!D", "belakang": "%!@#B",
  "kanan": "$!@#K", "kiri": "*!#@K", "atas": "%@#A", "bawah": "^!@B",
  "malam": "M!@#", "pagi": "!@P#", "siang": "$!#S", "sore": "*!@S",
  "terima": "$#&T", "kasih": "@#&K", "maaf": "M!F#", "tolong": "T!@L",
  "kemarin": "K!@#M", "hari": "H!R$", "rumah": "R!@#M",
  "sekolah": "S!#@K", "kantor": "K!@#N", "pasar": "P!@#S",
  "toko": "T!@#K", "uang": "U!@#G", "mahal": "M!@#H", "murah": "M!@#R",
  "tulis": "T!@#L", "baca": "B!@#C", "jalan": "J!@#L", "makan": "M!@#K",
  "minum": "M!@#N", "kerja": "K!@#J", "tidur": "T!@#D",
  "dengar": "D!@#N", "lihat": "L!@#H", "rasa": "R!@#S", "pikir": "P!@#K",
  "mengubah": "#@*&^%", "membuat": "$!&@*", "menjadi": "_#*&$",
  "mungkin": "$%_#$", "pada": "@!P_", "saya": "_#Y$",
  "sekarang": "#$@&_!_#", "sudah": "&%_!*", "tentang": "*@#&_T!",
  "yang": "@_Y@&",

  // Kata sambung dan tata bahasa
  "dan": "d@n!", "atau": "a!@u^", "karena": "k*r!N@",
  "sehingga": "s!h!Ng^", "jika": "j!k@#", "maka": "m@k^!",
  "meskipun": "m_sk!pUn", "walaupun": "wLp_n", "supaya": "s!p@y^",
  "agar": "aG@r$", "untuk": "uNt*k", "dengan": "d!n!g^n",
  "tanpa": "t@np!", "selain": "s!L@!N", "bersama": "b!s@m^",
  "terhadap": "t!rh@d^p", "sebagai": "s!b@g@i",
  "seperti": "s!p3rt!", "bahkan": "b@hk!n", "melainkan": "m!l@!nkN",
  "bukan": "b!k@N", "hanya": "h@Ny^", "saja": "s@j!$",
  "pun": "p!n_", "juga": "j!g^", "pula": "p!L@", "lagi": "l@g!#",
  "sekali": "s!k@l!", "sangat": "s@nG!t", "amat": "a!m@t",
  "terlalu": "t!rL@lu", "begitu": "b!g!tU", "demikian": "d!m!k!@n",
  "di": "d!*", "ke": "k!@", "dari": "d#r!*",

  // Kata Sehari-hari yang sering digunakan
  "halo": "h@lo!", "kalian": "k@L!@n", "ngapain": "nG!p@!n",
  "disini": "d!s!n!", "apa": "k*5?", "apakah": "k@1$?",
  "gimana": "g!m#n1", "kenapa": "kn!&pA", "bagaimana": "b@g_M!N",
  "siapa": "s!_p@", "siapapun": "s!_p@1", "kemana": "k!m@N^",
  "dimana": "d!m@n_", "kapan": "k!p@n$", "belum": "bL!m$",
  "nanti": "n@!nT1", "tapi": "t#p!*", "oke": "oK#e!",
  "iya": "iY@&", "tidak": "tD!_@k", "mau": "m@u*", "bisa": "b!s@!",
  "punya": "p!nY@$", "kamu": "k!@m!u", "dia": "d!@*", "kita": "k!t@#",
  "mereka": "m!r@k$", "apa-apa": "k*5?-k*5?", "apa-apaan": "k*5?-paaN",
  "sekarang": "#$@&_!_#",

  // Kata Kerja (Verba)
  "memiliki": "m!m!l!k!", "mendapatkan": "m!nd!p!tk!n", "memberi": "m!mb!r!",
  "mengambil": "m!ng@mb!l", "menemukan": "m!n!m!k!n", "menyimpan": "m!ny!mp@n",
  "menggunakan": "m!ngg!n@k!n", "memulai": "m!m!l@!", "menyelesaikan": "m!ny!l!s@ik!n",
  "menolong": "m!n!l!nG", "membantu": "m!mb!ntu", "merawat": "m!r@w@t",
  "menjaga": "m!nj!g@", "menghancurkan": "m!ngh@nc!rk!n",
  "membangun": "m!mb@ng!n", "mendengarkan": "m!nd!ng@rk!n",
  "mencium": "m!nc!um", "merasakan": "m!r@s@k!n",
  "duduk": "d!D!k", "berdiri": "b!rd!r!", "berbaring": "b!rb!r!ng",
  "jatuh": "j!t!h", "terbang": "t!rb@ng", "berenang": "b!r!n@ng",
  "mengemudi": "m!ng!m!d!", "membawa": "m!mb@wA", "memakai": "m!m@k@!",
  "melepas": "m!l!p@s", "mencuci": "m!nc!c!", "memasak": "m!m@s@k",
  "makan": "m@k@n", "minum": "m!n!m", "membayar": "m!mb@y@r",
  "menjual": "m!nj!@l", "membeli": "m!mb!l!", "bekerja": "b!k!rjA",
  "belajar": "b!l!j@r", "mengajar": "m!ng@j@r", "menulis": "m!n!l!s",
  "membaca": "m!mb@c@", "berpikir": "b!rp!k!r", "mengerti": "m!ng!rt!",
  "percaya": "p!rc@yA", "tahu": "t@h!u", "lupa": "l!p@!", "ingat": "i!ng@t",
  "menunggu": "m!n!nggu", "datang": "d@t!ng", "pergi": "p!rg!",
  "pulang": "p!l@ng", "tiba": "t!b@!", "kembali": "k!mb@l!",
  "hadir": "h@d!r", "absen": "a!bs!n", "bertambah": "b!rt!mb!h",
  "berkurang": "b!rk!r!ng", "memotong": "m!m!t!ng", "menambah": "m!n!mb@h",
  "mengurangi": "m!ng!r!ng!", "mendorong": "m!nd!r!ng", "menarik": "m!n!r!k",

  // Kata Benda (Nomina)
  "dunia": "d!N!a", "manusia": "m@n!siA", "pemerintah": "p_m!r!nt#",
  "negara": "n!g^ra", "masyarakat": "m@sy!r#k@t", "kota": "kO!tA",
  "desa": "d!S@", "bumi": "b!M!i", "langit": "l@nG!T",
  "matahari": "m!t@h@r!", "bulan": "b!L@n", "bintang": "b!nt@nG",
  "air": "a!R", "api": "aP!i", "angin": "aNg!n", "tanah": "t@n#h",
  "makanan": "m!k@Nn!", "minuman": "m!n!m@N", "pakaian": "p@k!An",
  "hewan": "h!w@N", "tumbuhan": "t!mb!h@n", "transportasi": "t_r@nsP!rt!s!",
  "sejarah": "s!j@R#h", "ilmu": "iLm!", "pengetahuan": "p!n!g!t@Hn",
  "teknologi": "t!k-n!l!g!", "seni": "s!N!i", "musik": "m!S!k",
  "olahraga": "oL!hr@gA", "kesehatan": "k!s!h@T#n", "pendidikan": "p!nd!d!k@n",
  "bisnis": "b!sn!s$", "ekonomi": "eK!nOmi", "hukum": "h!K!m",
  "politik": "p!l!t!k", "agama": "aG!m@", "budaya": "b!d@y^",
  "keluarga": "k!l!rgA", "teman": "t!m@N", "saudara": "s@!d!ra",
  "anak": "a!n@k", "ayah": "a!y@h", "ibu": "iB!u",
  "orangtua": "oR!nt!a", "cinta": "c!nt^", "sayang": "s!y@nG",
  "pria": "p!r!a", "wanita": "w!n!tA", "laki-laki": "l@k!-l@k!",
  "perempuan": "p!r!mp!@n", "istri": "i!str!", "suami": "s!@m!",
  "adik": "a!d!k", "kakak": "k!k@k", "orang": "o!r@ng",
  "jalanan": "j!l!n@n", "rumah": "r!m@h", "gedung": "g!d!ng",
  "kantor": "k!nt!r", "pasar": "p!s@r", "toko": "t!k!",
  "hotel": "h!t!l", "restoran": "r!st!r@n", "stasiun": "st!si!n",
  "bandara": "b!nd@rA", "pelabuhan": "p!l!b!h@n", "jalan": "j!l@n",
  "jembatan": "j!mb@t@n", "sungai": "s!ng@i", "danau": "d!n@u",
  "laut": "l@ut", "gunung": "g!n!ng", "hutan": "h!t@n",
  "pohon": "p!h!n", "bunga": "b!ng@", "buah": "b!@h",
  "sayur": "s!y!r", "daging": "d!g!ng", "roti": "r!t!",
  "nasi": "n!s!", "minyak": "m!ny!k", "gula": "g!lA",
  "garam": "g!r@m", "air": "a!r", "teh": "t!h",
  "kopi": "k!p!", "susu": "s!s!", "rokok": "r!k!k",
  "mobil": "m!b!l", "motor": "m!t!r", "sepeda": "s!p!d@",
  "bus": "b!s", "kereta": "k!r!tA", "pesawat": "p!s@w@t",
  "kapal": "k!p@l", "uang": "u!ng", "harga": "h!rgA",
  "diskon": "d!sk!n", "bonus": "b!n!s", "pajak": "p!j@k",
  "biaya": "b!y@y@", "duit": "d!it", "pekerjaan": "p!k!rj@n",

  // Kata Sifat (Adjektiva)
  "bahagia": "b!h!g!a", "sedih": "s!d!h", "marah": "m@r#h",
  "takut": "t@k!t", "kecewa": "k!c!w@", "cinta": "c!nt^", "benci": "b!nc!",
  "suka": "s!K@!", "senang": "s!n@ng", "gembira": "g!mb!rA",
  "murung": "m!r!ng", "kesal": "k!s@l", "khawatir": "kh@w@t!r",
  "terkejut": "t!rk!j!t", "lelah": "l!l@h", "capek": "c!p!k",
  "lapar": "l!p@r", "haus": "h@us", "sehat": "s!h@t", "sakit": "s!k!t",
  "baik": "b!ik", "buruk": "b!r!k", "bagus": "b!g!s", "jelek": "j!l!k",
  "besar": "b!s@r", "kecil": "k!c!l", "panjang": "p@nj!ng",
  "pendek": "p!nd!k", "tinggi": "t!ngg!", "rendah": "r!nd@h",
  "berat": "b!r@t", "ringan": "r!ng@n", "kuat": "k!@t", "lemah": "l!m@h",
  "kaya": "k!yA", "miskin": "m!sk!n", "pintar": "p!nt@r",
  "bodoh": "b!d!h", "ramai": "r@m!i", "sepi": "s!p!",
  "bersih": "b!rs!h", "kotor": "k!t!r", "baru": "b!r!",
  "lama": "l@m@", "tua": "t!@", "muda": "m!dA", "hitam": "h!t@m",
  "putih": "p!t!h", "merah": "m!r@h", "biru": "b!r!u",
  "hijau": "h!j@u", "kuning": "k!n!ng", "coklat": "c!kl@t",
  "abu-abu": "a!bu-a!bu", "emas": "e!m@s", "perak": "p!r@k",

  // Waktu dan Angka
  "pagi": "p@g!", "siang": "s!@ng", "sore": "s!r!", "malam": "m@l@m",
  "kemarin": "k!m@r!n", "besok": "b!s!k", "lusa": "l!s@",
  "minggu": "m!ngg!", "bulan": "b!l@n", "tahun": "t@h!n",
  "detik": "d!t!k", "menit": "m!n!t", "jam": "j@m", "hari": "h!r!",
  "januari": "j!n!r!", "februari": "f!br!r!", "maret": "m@r!t",
  "april": "a!pr!l", "mei": "m!i", "juni": "j!n!", "juli": "j!l!",
  "agustus": "a!g!st!s", "september": "s!pt!mb!r", "oktober": "o!kt!b!r",
  "november": "n!v!mb!r", "desember": "d!s!mb!r",
  "senin": "s!n!n", "selasa": "s!l@s@", "rabu": "r!b!",
  "kamis": "k!m!s", "jumat": "j!m@t", "sabtu": "s@bt!u",
  "satu": "1#&", "dua": "2$!", "tiga": "3&^", "empat": "4_*",
  "lima": "5!@#", "enam": "6$!#", "tujuh": "7&%^",
  "delapan": "8!@#*", "sembilan": "9*&@#", "sepuluh": "10!@#$",
  "seratus": "100_@#", "seribu": "1000^!&",
  "sejuta": "1000000!@#$", "semiliar": "1000000000!@#$",
};
